files: api
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: sort-simple-yaml
      - id: check-toml
      - id: check-merge-conflict
      - id: check-yaml
  - repo: local
    hooks:
      - id: black
        name: black
        language: python
        types: [python]
        entry: black
      - id: ruff
        name: ruff
        language: python
        types: [python]
        entry: ruff
      - id: mypy
        name: mypy
        language: python
        types: [python]
        entry: mypy --implicit-optional
