version: '3'
services:

  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    restart: unless-stopped

  default_broker:
    image: docker.vectorized.io/vectorized/redpanda:v21.9.5
    command:
     - redpanda start
     - --overprovisioned
     - --smp 1
     - --memory 1G
     - --reserve-memory 0M
     - --node-id 0
     - --check=false
     - --kafka-addr 0.0.0.0:9092
     - --advertise-kafka-addr default_broker:9092
     - --pandaproxy-addr 0.0.0.0:8082
     - --advertise-pandaproxy-addr default_broker:8082
    environment:
      - AUTO_CREATE_TOPICS_ENABLED=true
    ports:
     - 9092:9092
     - 8081:8081
     - 8082:8082

  default_processor:
    image: materialize/materialized:v0.12.0
    container_name: materialize
    command: -w1 --disable-telemetry
    ports:
      - 6875:6875

  redis:
    image: 'bitnami/redis:latest'
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379

  default_runner:
    build: api
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
    command: celery -A api.experiments worker
    depends_on:
      - redis
      - db
      - default_broker
      - default_processor

  api:
    build: api
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
    ports:
      - 8000:8000
    volumes:
      - ./api:/code
    command: >
      bash -c "
        python init_db.py &&
        uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload --reload-dir /code
      "
    depends_on:
      - db
      - default_broker
      - default_processor
      - default_runner

  ui:
    build: ui
    volumes:
      - ./ui:/code
      - node_modules:/code/node_modules
    environment:
      NUXT_HOST: 0.0.0.0
    command: yarn run dev
    ports:
      - 3000:3000
    depends_on:
      - api

volumes:
  postgres:
  node_modules:
